# Generated by Django 5.2.1 on 2025-05-20 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('named_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя URL')),
                ('menu_name', models.CharField(db_index=True, max_length=100, verbose_name='Название меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.menuitem', verbose_name='Родитель')),
            ],
        ),
    ]
